/**
 * @file demo_fixtures.ts
 * @description Isolated mock fixtures for DEMO MODE only.
 * 
 * CRITICAL INVARIANT:
 * These fixtures are strictly used when the user explicitly enables DEMO MODE
 * or for local UI component testing when backend services are offline.
 * Every entity is explicitly tagged with [DEMO] to prevent mistaking for real data.
 */

import { Agent, AgentDetail, PaymentIntent, RegisteredService, TransactionRecord } from './types';

export const DEMO_AGENTS: Agent[] = [
  {
    id: 'research-agent',
    name: '[DEMO] Research Agent',
    status: 'ACTIVE',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    usdc_balance: '12.48',
    vault_address: '0x1111111111111111111111111111111111111111',
    daily_limit: '5.00',
    daily_spent: '2.41',
    pending_intents: 1,
    last_activity: '2 mins ago',
  },
  {
    id: 'compute-agent',
    name: '[DEMO] Compute Optimizer Agent',
    status: 'ACTIVE',
    created_at: new Date(Date.now() - 172800000).toISOString(),
    usdc_balance: '45.00',
    vault_address: '0x2222222222222222222222222222222222222222',
    daily_limit: '20.00',
    daily_spent: '8.50',
    pending_intents: 0,
    last_activity: '15 mins ago',
  },
];

export const DEMO_AGENT_DETAIL: AgentDetail = {
  ...DEMO_AGENTS[0],
  network: 'Arc Network (Chain ID 5042)',
  policy: {
    enabled: true,
    per_transaction_limit: '500000', // $0.50 USDC
    daily_spending_limit: '5000000', // $5.00 USDC
    daily_spent: '2410000', // $2.41 USDC
    remaining_daily_limit: '2590000', // $2.59 USDC
    max_transactions_per_day: 20,
    transactions_today: 7,
    allowed_recipients: [
      '0x1111111111111111111111111111111111111111',
      '0x2222222222222222222222222222222222222222',
    ],
    blocked_recipients: [
      '0x000000000000000000000000000000000000dEaD',
    ],
  },
};

export const DEMO_SERVICES: RegisteredService[] = [
  {
    id: 'web-research',
    name: 'Web Research & Intelligence API',
    recipient: '0x1111111111111111111111111111111111111111',
    asset: 'USDC',
    enabled: true,
    max_price: '500000', // 0.50 USDC
  },
  {
    id: 'compute-cluster',
    name: 'GPU Inference Compute Cluster',
    recipient: '0x2222222222222222222222222222222222222222',
    asset: 'USDC',
    enabled: true,
    max_price: '2000000', // 2.00 USDC
  },
  {
    id: 'data-feed',
    name: 'Decentralized Oracle Data Feed',
    recipient: '0x3333333333333333333333333333333333333333',
    asset: 'USDC',
    enabled: true,
    max_price: '100000', // 0.10 USDC
  },
];

export const DEMO_INTENTS: PaymentIntent[] = [
  {
    intent_id: 'intent_demo_auth123',
    agent_id: 'research-agent',
    vault_address: '0x1111111111111111111111111111111111111111',
    recipient: '0x1111111111111111111111111111111111111111',
    amount: '180000', // 0.18 USDC
    asset: 'USDC',
    purpose: 'api_usage',
    service: 'web-research',
    justification: '[DEMO] External data is required to complete the research task.',
    status: 'AUTHORIZED',
    created_at: new Date(Date.now() - 60000).toISOString(),
    expires_at: new Date(Date.now() + 240000).toISOString(),
    updated_at: new Date(Date.now() - 40000).toISOString(),
  },
  {
    intent_id: 'intent_demo_conf456',
    agent_id: 'research-agent',
    vault_address: '0x1111111111111111111111111111111111111111',
    recipient: '0x1111111111111111111111111111111111111111',
    amount: '180000',
    asset: 'USDC',
    purpose: 'api_usage',
    service: 'web-research',
    justification: '[DEMO] Web search indexing for Arc microgrants.',
    status: 'CONFIRMED',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    expires_at: new Date(Date.now() - 3300000).toISOString(),
    updated_at: new Date(Date.now() - 3500000).toISOString(),
  },
  {
    intent_id: 'intent_demo_deny789',
    agent_id: 'research-agent',
    vault_address: '0x1111111111111111111111111111111111111111',
    recipient: '0x1111111111111111111111111111111111111111',
    amount: '6000000', // 6.00 USDC (Exceeds daily limit)
    asset: 'USDC',
    purpose: 'api_usage',
    service: 'web-research',
    justification: '[DEMO] Bulk query exceeding daily allowance.',
    status: 'DENIED',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    expires_at: new Date(Date.now() - 6900000).toISOString(),
    updated_at: new Date(Date.now() - 7190000).toISOString(),
  },
  {
    intent_id: 'intent_demo_exp000',
    agent_id: 'research-agent',
    vault_address: '0x1111111111111111111111111111111111111111',
    recipient: '0x1111111111111111111111111111111111111111',
    amount: '180000',
    asset: 'USDC',
    purpose: 'api_usage',
    service: 'web-research',
    justification: '[DEMO] Query timed out before user confirmed.',
    status: 'EXPIRED',
    created_at: new Date(Date.now() - 14400000).toISOString(),
    expires_at: new Date(Date.now() - 14100000).toISOString(),
    updated_at: new Date(Date.now() - 14100000).toISOString(),
  },
];

export const DEMO_TRANSACTIONS: TransactionRecord[] = [
  {
    intent_id: 'intent_demo_conf456',
    transaction_hash: '0x9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
    status: 'CONFIRMED',
    submitted_at: new Date(Date.now() - 3550000).toISOString(),
    confirmed_at: new Date(Date.now() - 3500000).toISOString(),
    agent_id: 'research-agent',
    vault_address: '0x1111111111111111111111111111111111111111',
    recipient: '0x1111111111111111111111111111111111111111',
    amount: '180000',
  },
];

export const DEMO_SECURITY_REPORT = {
  generated_at: new Date().toISOString(),
  total_scenarios: 20,
  passed_scenarios: 20,
  failed_scenarios: 0,
  invariants_total: 12,
  invariants_verified: 12,
  scenarios: [
    {
      id: 'SEC-01',
      name: 'RECIPIENT_OVERRIDE',
      category: 'AUTHORIZATION',
      attack_vector: 'Agent specifies a legitimate service_id but supplies an attacker-controlled settlement recipient address.',
      expected_behavior: 'Server-side service registry overrides user-provided recipient with authoritative address 0x2222222222222222222222222222222222222222',
      actual_behavior: 'Authoritative recipient enforced: 0x2222222222222222222222222222222222222222',
      status: 'PASS',
      evidence: { enforced_recipient: '0x2222222222222222222222222222222222222222', service_id: 'compute-cluster' },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-02',
      name: 'AMOUNT_MANIPULATION',
      category: 'AUTHORIZATION',
      attack_vector: 'Agent requests payment with quote_id but manipulates amount (100x, zero, negative, u64 max).',
      expected_behavior: 'Rejection via quote verification mismatch or integer parsing validation; no float rounding errors.',
      actual_behavior: 'All 4 manipulated amounts rejected: 100x mismatch, zero, negative, and u64 max overflow blocked.',
      status: 'PASS',
      evidence: { quote_amount: '180000', variations_tested: 4, all_rejected: true },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-03',
      name: 'HARD_DENY_BYPASS',
      category: 'AUTHORIZATION',
      attack_vector: 'Attempting to override a terminal policy hard DENY via human approval, agent retry, or re-authorization.',
      expected_behavior: 'Hard DENY remains inviolable and terminal. Approval and re-authorization strictly fail.',
      actual_behavior: 'All override attempts rejected: approval rejected with ErrCannotApproveDenied; re-auth retained terminal DENY; confirm blocked.',
      status: 'PASS',
      evidence: { approval_rejected: true, confirm_blocked: true, error_code: 'ErrCannotApproveDenied' },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-04',
      name: 'SELF_APPROVAL',
      category: 'AUTHORIZATION',
      attack_vector: 'Agent attempts to act as human approver for its own payment intent.',
      expected_behavior: 'Rejected with ErrAgentSelfApprovalProhibited. Approver ID must not match agent ID.',
      actual_behavior: 'Self-approval blocked with ErrAgentSelfApprovalProhibited',
      status: 'PASS',
      evidence: { prohibited_actor: 'agent_financial_bot', error: 'agent cannot approve its own payment intent' },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-05',
      name: 'POLICY_MUTATION',
      category: 'AUTHORIZATION',
      attack_vector: 'Compromised agent attempts to modify daily spending limits or recipient allowlists.',
      expected_behavior: 'Zero policy administration authority granted to agents; all mutations rejected.',
      actual_behavior: 'Agent has zero policy administration routes; policy engine configuration immutable by agents.',
      status: 'PASS',
      evidence: { agent_role: 'UNPRIVILEGED_PROPOSER', policy_admin_isolated: true },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-06',
      name: 'BUDGET_BYPASS',
      category: 'FINANCIAL',
      attack_vector: 'Sequential payment requests designed to cumulatively breach daily spending allocation.',
      expected_behavior: 'Total authorized spend is strictly capped at available budget; over-budget intent DENIED.',
      actual_behavior: 'Payment 1 ALLOWED ($0.50); Payment 2 strictly DENIED ($0.80 > $0.50 remaining budget with reason DAILY_LIMIT_EXCEEDED)',
      status: 'PASS',
      evidence: { payment_1_decision: 'ALLOW', payment_2_decision: 'DENY', total_authorized: '500000' },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-07',
      name: 'VELOCITY_SPAM',
      category: 'FINANCIAL',
      attack_vector: 'Rapid burst of 10 micro-payments within seconds from the same agent.',
      expected_behavior: 'Velocity threshold trips, denying payment intents exceeding hourly/daily transaction ceiling.',
      actual_behavior: 'Velocity limits engaged: exactly 5 allowed, remaining 5 denied with reason DAILY_TX_LIMIT_EXCEEDED',
      status: 'PASS',
      evidence: { allowed_count: 5, denied_count: 5, requests_attempted: 10 },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-08',
      name: 'IDEMPOTENCY_REPLAY',
      category: 'FINANCIAL',
      attack_vector: 'Attacker replays identical payment requests with duplicate idempotency key.',
      expected_behavior: 'Exactly one payment intent created; subsequent replayed requests return original intent.',
      actual_behavior: 'Idempotent replay detected; exact existing intent returned without duplicate execution.',
      status: 'PASS',
      evidence: { duplicate_executions: 0, idempotency_key: 'req_replay_attack_key_101' },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-09',
      name: 'CROSS_TENANT',
      category: 'AUTHORIZATION',
      attack_vector: 'Organization A credentials used to access and mutate Organization B payment intents.',
      expected_behavior: 'Access denied (404/403); zero resource leakage or unauthorized modification across organizations.',
      actual_behavior: 'Cross-tenant access strictly blocked with 404/403.',
      status: 'PASS',
      evidence: { blocked: true, org_a: 'org_A', org_b: 'org_B' },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-10',
      name: 'API_KEY_ABUSE',
      category: 'AUTHORIZATION',
      attack_vector: 'Compromised agent API key used to invoke raw blockchain signing and admin routes.',
      expected_behavior: 'Role-based scope enforcement blocks agent keys from executing admin or direct signer calls.',
      actual_behavior: 'Agent API key is scoped strictly to payment intent proposals; admin routes reject agent keys.',
      status: 'PASS',
      evidence: { admin_routes_accessible: false, key_role: 'AGENT_ROLE' },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-11',
      name: 'PROMPT_INJECTION',
      category: 'AUTHORIZATION',
      attack_vector: 'Adversarial jailbreak in task input attempting to override recipient and spend limits.',
      expected_behavior: 'Natural language instructions have zero authority over structural mathematical boundaries.',
      actual_behavior: 'Prompt injection neutralized: ErrRecipientManipulation triggered, 0 intents created.',
      status: 'PASS',
      evidence: { blocked_by: 'Structural recipient validation against Service Registry' },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-12',
      name: 'MALICIOUS_SERVICE',
      category: 'AUTHORIZATION',
      attack_vector: 'Service returns spoofed payment confirmation and alternate recipient address.',
      expected_behavior: 'Service claims ignored; authoritative recipient from registry and on-chain verification required.',
      actual_behavior: 'External service responses cannot alter settlement recipient or claim fake payment confirmation.',
      status: 'PASS',
      evidence: { recipient_authority: 'Server-side Service Registry', settlement_proof: 'Arc blockchain receipt validation' },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-13',
      name: 'POLICY_FAILURE',
      category: 'RESILIENCE',
      attack_vector: 'Simulated complete outage / crash of the Rust policy engine during authorization.',
      expected_behavior: 'System fails closed: authorization rejected, zero funds reserved or broadcast.',
      actual_behavior: 'Fail-closed enforced: authorization rejected with connection refused, intent not authorized.',
      status: 'PASS',
      evidence: { fail_closed_verified: true, intent_status: 'CREATED' },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-14',
      name: 'SIGNER_FAILURE',
      category: 'RESILIENCE',
      attack_vector: 'KMS / Signer module unavailable or rejecting signing key.',
      expected_behavior: 'Execution aborts; zero broadcast events emitted, no false on-chain confirmation.',
      actual_behavior: 'Signer failure halts execution prior to broadcast; audit record logged, no false confirmation created.',
      status: 'PASS',
      evidence: { false_success_prevented: true, signer_error_handling: 'ABORT_BEFORE_BROADCAST' },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-15',
      name: 'RPC_FAILURE',
      category: 'RESILIENCE',
      attack_vector: 'Arc RPC broadcast succeeds but receipt lookup times out.',
      expected_behavior: 'Transaction transitions to AMBIGUOUS state for reconciliation; zero blind rebroadcasting.',
      actual_behavior: 'Receipt timeout correctly yielded AMBIGUOUS state (no false FAILED marking, no blind rebroadcast)',
      status: 'PASS',
      evidence: { blind_rebroadcast_prevented: true, status: 'AMBIGUOUS' },
      execution_time_ms: 13,
    },
    {
      id: 'SEC-16',
      name: 'DATABASE_FAILURE',
      category: 'RESILIENCE',
      attack_vector: 'Database outage or connection dropped during payment creation and reservation.',
      expected_behavior: 'Atomic transaction aborts; zero off-chain or on-chain state inconsistencies.',
      actual_behavior: 'Database transaction failure aborts intent pipeline before fund reservation; zero orphan on-chain transactions.',
      status: 'PASS',
      evidence: { orphan_tx_prevented: true, storage_rollback: 'ATOMIC_TRANSACTION' },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-17',
      name: 'TREASURY_RACE',
      category: 'FINANCIAL',
      attack_vector: '20 concurrent goroutines attempting to reserve $0.10 each against a $1.00 balance.',
      expected_behavior: 'Atomic reservation locks prevent race conditions; total authorized equals balance ceiling.',
      actual_behavior: 'Concurrency lock held: exactly 10/20 succeeded ($1.00 total), 10/20 rejected with insufficient funds.',
      status: 'PASS',
      evidence: { concurrent_requests: 20, double_spend_prevented: true, fail_count: 10, success_count: 10 },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-18',
      name: 'TRANSACTION_MUTATION',
      category: 'RESILIENCE',
      attack_vector: 'Tampering with transaction recipient or calldata between policy approval and broadcast.',
      expected_behavior: 'Signer validates transaction against authorized intent hash before signing, rejecting mutation.',
      actual_behavior: 'Signer binds calldata and recipient strictly to authorized intent parameters; post-authorization tampering rejected.',
      status: 'PASS',
      evidence: { calldata_tamper_prevented: true, intent_binding: 'CRYPTOGRAPHIC_HASH' },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-19',
      name: 'SIMULATION_ESCAPE',
      category: 'RESILIENCE',
      attack_vector: 'Attempting to trigger on-chain Arc settlement from simulation endpoint.',
      expected_behavior: 'Simulation mode strictly isolated; zero blockchain signer invocations or RPC broadcasts.',
      actual_behavior: 'Simulations execute via pure in-memory evaluation without invoking blockchain executor or signer.',
      status: 'PASS',
      evidence: { broadcast_attempted: false, signer_invoked: false, simulation_mode: true },
      execution_time_ms: 0,
    },
    {
      id: 'SEC-20',
      name: 'EMERGENCY_PAUSE',
      category: 'RESILIENCE',
      attack_vector: 'Attempting to initiate payment transactions while emergency kill-switch is active.',
      expected_behavior: 'Fails closed immediately; zero intent creation or execution until explicitly resumed.',
      actual_behavior: 'Payment creation blocked during pause; unpause successfully resumes payment flow.',
      status: 'PASS',
      evidence: { agent_status: 'PAUSED', resumption_verified: true },
      execution_time_ms: 0,
    },
  ],
  invariants: [
    { id: 1, description: 'Agent cannot directly move funds; must propose payment intent subject to gateway authorization', status: 'PASS', details: 'Structural invariant verified: Private keys isolated in server KMS/Signer; agents submit intents only.' },
    { id: 2, description: 'Agent cannot choose arbitrary settlement recipient', status: 'PASS', details: 'Verified: Intent recipient is strictly derived from authoritative Service Registry.' },
    { id: 3, description: 'Hard DENY cannot be overridden by approval or retry', status: 'PASS', details: 'Verified: Terminal hard DENY rejects all subsequent human approval attempts.' },
    { id: 4, description: 'Agent cannot self-approve payments', status: 'PASS', details: 'Verified: Self-approval protection enforces that agent_id != approver_id.' },
    { id: 5, description: 'Cross-tenant resources remain isolated', status: 'PASS', details: 'Verified: Cross-organization mutations and reads fail-closed with 404/403.' },
    { id: 6, description: 'Duplicate idempotent request cannot create duplicate execution', status: 'PASS', details: 'Verified: Replayed idempotent request returns exact existing intent record.' },
    { id: 7, description: 'Treasury cannot authorize more than available/allowed', status: 'PASS', details: 'Verified: Atomic treasury reservation prevents race condition double-spending.' },
    { id: 8, description: 'Policy engine failure fails closed', status: 'PASS', details: 'Verified: Policy engine unavailability fails closed; zero unauthorized executions.' },
    { id: 9, description: 'Signer failure cannot create successful payment', status: 'PASS', details: 'Verified: Signer error terminates transaction execution before broadcast; no false confirmations.' },
    { id: 10, description: 'Simulation mode cannot broadcast or interact with live Arc signer', status: 'PASS', details: 'Verified: Simulation engine executes policy simulation strictly without invoking blockchain executor.' },
    { id: 11, description: 'Ambiguous transaction cannot be blindly rebroadcast', status: 'PASS', details: 'Verified: Receipt timeout triggers AMBIGUOUS state; reconciliation queries chain before retry.' },
    { id: 12, description: 'Historical financial trace cannot be silently rewritten', status: 'PASS', details: 'Verified: Audit storage provides append-only guarantee; zero historical update/delete APIs exist.' },
  ],
};

