-- 000011_durable_runtime.down.sql
DROP TABLE IF EXISTS runtime_incidents CASCADE;
DROP TABLE IF EXISTS scheduled_jobs CASCADE;
DROP TABLE IF EXISTS inbox_events CASCADE;
DROP TABLE IF EXISTS outbox_events CASCADE;
DROP TABLE IF EXISTS runtime_decisions CASCADE;
DROP TABLE IF EXISTS workers CASCADE;
DROP TABLE IF EXISTS checkpoints CASCADE;
DROP TABLE IF EXISTS leases CASCADE;
DROP TABLE IF EXISTS execution_steps CASCADE;
DROP TABLE IF EXISTS workflows CASCADE;
