package intent

import (
	"time"
)

// IntentStatus represents the lifecycle state of a PaymentIntent.
type IntentStatus string

const (
	StatusCreated    IntentStatus = "CREATED"
	StatusAuthorized IntentStatus = "AUTHORIZED"
	StatusDenied     IntentStatus = "DENIED"
	StatusExecuting  IntentStatus = "EXECUTING"
	StatusSubmitted  IntentStatus = "SUBMITTED"
	StatusConfirmed  IntentStatus = "CONFIRMED"
	StatusFailed     IntentStatus = "FAILED"
	StatusExpired    IntentStatus = "EXPIRED"
)

// PaymentIntent represents a structured economic payment intent generated by an AI agent.
type PaymentIntent struct {
	IntentID      string       `json:"intent_id"`
	AgentID       string       `json:"agent_id"`
	VaultAddress  string       `json:"vault_address"`
	Recipient     string       `json:"recipient"` // Server-resolved approved recipient
	Amount        string       `json:"amount"`    // Integer base units string (e.g. "180000")
	Asset         string       `json:"asset"`     // "USDC"
	Purpose       string       `json:"purpose"`
	ServiceID     string       `json:"service"`
	Justification string       `json:"justification"`
	Status        IntentStatus `json:"status"`
	CreatedAt     time.Time    `json:"created_at"`
	ExpiresAt     time.Time    `json:"expires_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}

// PaymentExecutionRecord holds correlated blockchain transaction data for a payment intent.
type PaymentExecutionRecord struct {
	IntentID        string     `json:"intent_id"`
	TransactionHash string     `json:"transaction_hash,omitempty"`
	Status          string     `json:"status"`
	SubmittedAt     *time.Time `json:"submitted_at,omitempty"`
	ConfirmedAt     *time.Time `json:"confirmed_at,omitempty"`
	ErrorCode       string     `json:"error_code,omitempty"`
}
