'use client';

import React, { useEffect, useState } from 'react';
import { IntentTable } from '../../components/IntentTable';
import { EmptyState } from '../../components/EmptyState';
import { ErrorState } from '../../components/ErrorState';
import { fetchIntents } from '../../lib/api/intents';
import { PaymentIntent } from '../../lib/api/types';
import { DEMO_INTENTS } from '../../lib/api/demo_fixtures';

const STATUS_TABS = ['ALL', 'AUTHORIZED', 'CONFIRMED', 'CREATED', 'DENIED', 'EXPIRED'];

export default function PaymentIntentsPage() {
  const [intents, setIntents] = useState<PaymentIntent[]>([]);
  const [activeTab, setActiveTab] = useState('ALL');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isDemoMode, setIsDemoMode] = useState(false);

  const loadIntents = async (useDemo: boolean, tab: string) => {
    setLoading(true);
    setError(null);

    if (useDemo) {
      const filtered =
        tab === 'ALL' ? DEMO_INTENTS : DEMO_INTENTS.filter((i) => i.status === tab);
      setIntents(filtered);
      setLoading(false);
      return;
    }

    try {
      const data = await fetchIntents(tab === 'ALL' ? undefined : tab);
      setIntents(data);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Failed to load payment intents';
      setError(msg);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadIntents(isDemoMode, activeTab);
  }, [isDemoMode, activeTab]);

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-[#222222]">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-[#F2F0EA]">Payment Intents</h1>
          <p className="text-xs text-[#716F69] mt-1">
            Economic requests generated by AI agents and evaluated by the deterministic policy engine.
          </p>
        </div>

        <button
          type="button"
          onClick={() => setIsDemoMode(!isDemoMode)}
          className={`px-2.5 py-1 rounded-md text-[11px] font-mono border self-start sm:self-auto transition-colors ${
            isDemoMode
              ? 'bg-[#141414] text-[#D6A83A] border-[#D6A83A]/40'
              : 'bg-[#141414] text-[#716F69] border-[#222222] hover:text-[#F2F0EA]'
          }`}
        >
          {isDemoMode ? '● DEMO MODE ACTIVE' : '○ Enable Demo Mode'}
        </button>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center gap-1.5 overflow-x-auto pb-1 text-xs font-mono">
        {STATUS_TABS.map((tab) => (
          <button
            key={tab}
            type="button"
            onClick={() => setActiveTab(tab)}
            className={`px-3 py-1.5 rounded-lg transition-colors whitespace-nowrap ${
              activeTab === tab
                ? 'bg-[#D6A83A] text-[#080808] font-bold'
                : 'text-[#716F69] hover:text-[#F2F0EA] hover:bg-[#141414] border border-[#222222]'
            }`}
          >
            {tab}
          </button>
        ))}
      </div>

      {error && !isDemoMode && (
        <ErrorState
          title="Payment Intents Unavailable"
          message={error}
          onRetry={() => loadIntents(false, activeTab)}
          isRetrying={loading}
        />
      )}

      {loading ? (
        <div className="h-64 rounded-xl bg-[#101010] border border-[#222222] animate-pulse" />
      ) : intents.length === 0 ? (
        <EmptyState
          title="No Payment Intents Found"
          description={`There are currently no payment intents in '${activeTab}' status.`}
          actionText="Load Demo Intents"
          onAction={() => setIsDemoMode(true)}
        />
      ) : (
        <IntentTable intents={intents} />
      )}
    </div>
  );
}
