package types

import (
	"encoding/json"
	"fmt"
	"strings"
)

// MissionPlan represents a structured mission decomposition generated by AI reasoning.
type MissionPlan struct {
	MissionID        string         `json:"mission_id"`
	Objective        string         `json:"objective"`
	Stages           []MissionStage `json:"stages"`
	EstimatedCostMax uint64         `json:"estimated_cost_max"`
	EstimatedTimeSec int            `json:"estimated_time_sec"`
	RiskAssessment   string         `json:"risk_assessment"`
}

type MissionStage struct {
	StageIndex         int      `json:"stage_index"`
	Name               string   `json:"name"`
	RequiredService    string   `json:"required_service"`
	Dependencies       []int    `json:"dependencies,omitempty"`
	MaxBudgetUSDC      uint64   `json:"max_budget_usdc"`
	AcceptanceCriteria []string `json:"acceptance_criteria"`
}

func (m *MissionPlan) Validate() error {
	if strings.TrimSpace(m.Objective) == "" {
		return fmt.Errorf("mission plan objective cannot be empty")
	}
	if len(m.Stages) == 0 {
		return fmt.Errorf("mission plan must contain at least one stage")
	}
	for i, stage := range m.Stages {
		if strings.TrimSpace(stage.Name) == "" {
			return fmt.Errorf("stage %d name cannot be empty", i)
		}
		if strings.TrimSpace(stage.RequiredService) == "" {
			return fmt.Errorf("stage %d required_service cannot be empty", i)
		}
	}
	return nil
}

// ServiceSelectionProposal represents an AI recommendation to select a commercial merchant service.
type ServiceSelectionProposal struct {
	ServiceID         string   `json:"service_id"`
	ProviderName      string   `json:"provider_name"`
	ProposedPriceUSDC uint64   `json:"proposed_price_usdc"`
	CapabilityScore   float64  `json:"capability_score"`
	LatencyEstimateMS int      `json:"latency_estimate_ms"`
	Reasoning         string   `json:"reasoning"`
	AlternativeIDs    []string `json:"alternative_ids,omitempty"`
}

func (s *ServiceSelectionProposal) Validate() error {
	if strings.TrimSpace(s.ServiceID) == "" {
		return fmt.Errorf("service_id cannot be empty")
	}
	if strings.TrimSpace(s.Reasoning) == "" {
		return fmt.Errorf("reasoning cannot be empty")
	}
	if s.CapabilityScore < 0.0 || s.CapabilityScore > 1.0 {
		return fmt.Errorf("capability_score must be between 0.0 and 1.0")
	}
	return nil
}

// NegotiationProposal represents an AI proposal during multi-round merchant price/SLA negotiation.
type NegotiationProposal struct {
	NegotiationID   string `json:"negotiation_id"`
	ServiceID       string `json:"service_id"`
	ProposedOffer   uint64 `json:"proposed_offer"`
	CounterParty    string `json:"counter_party"`
	Round           int    `json:"round"`
	TargetSLA       string `json:"target_sla"`
	ConcessionNotes string `json:"concession_notes"`
	FinalOffer      bool   `json:"final_offer"`
}

func (n *NegotiationProposal) Validate() error {
	if strings.TrimSpace(n.ServiceID) == "" {
		return fmt.Errorf("service_id cannot be empty")
	}
	if n.Round < 1 {
		return fmt.Errorf("negotiation round must be >= 1")
	}
	return nil
}

// ReplanProposal represents an AI adjustment when a mission encounters a failure or degraded service.
type ReplanProposal struct {
	OriginalMissionID string   `json:"original_mission_id"`
	FailedStageIndex  int      `json:"failed_stage_index"`
	FailureReason     string   `json:"failure_reason"`
	CorrectiveAction  string   `json:"corrective_action"`
	AlternateServices []string `json:"alternate_services"`
	AdjustedBudget    uint64   `json:"adjusted_budget"`
}

func (r *ReplanProposal) Validate() error {
	if strings.TrimSpace(r.OriginalMissionID) == "" {
		return fmt.Errorf("original_mission_id cannot be empty")
	}
	if strings.TrimSpace(r.FailureReason) == "" {
		return fmt.Errorf("failure_reason cannot be empty")
	}
	if strings.TrimSpace(r.CorrectiveAction) == "" {
		return fmt.Errorf("corrective_action cannot be empty")
	}
	return nil
}

// SwarmPlan represents coordinated sub-agent delegation.
type SwarmPlan struct {
	SwarmID         string                 `json:"swarm_id"`
	CoordinatorRole string                 `json:"coordinator_role"`
	SubAgents       []SwarmAgentAssignment `json:"sub_agents"`
	ConsensusPolicy string                 `json:"consensus_policy"`
	TotalBudgetCap  uint64                 `json:"total_budget_cap"`
}

type SwarmAgentAssignment struct {
	AgentID      string `json:"agent_id"`
	Role         string `json:"role"`
	AssignedTask string `json:"assigned_task"`
	MaxBudget    uint64 `json:"max_budget"`
}

func (s *SwarmPlan) Validate() error {
	if strings.TrimSpace(s.SwarmID) == "" {
		return fmt.Errorf("swarm_id cannot be empty")
	}
	if len(s.SubAgents) == 0 {
		return fmt.Errorf("swarm must have at least one sub_agent")
	}
	return nil
}

// ResultEvaluation represents the qualitative and semantic assessment of untrusted deliverable data.
type ResultEvaluation struct {
	ServiceID         string   `json:"service_id"`
	DeliverableDigest string   `json:"deliverable_digest"`
	Verified          bool     `json:"verified"`
	QualityScore      float64  `json:"quality_score"`
	SLACompliance     bool     `json:"sla_compliance"`
	Summary           string   `json:"summary"`
	AnomaliesDetected []string `json:"anomalies_detected,omitempty"`
}

func (r *ResultEvaluation) Validate() error {
	if strings.TrimSpace(r.ServiceID) == "" {
		return fmt.Errorf("service_id cannot be empty")
	}
	if r.QualityScore < 0.0 || r.QualityScore > 1.0 {
		return fmt.Errorf("quality_score must be between 0.0 and 1.0")
	}
	return nil
}

// EconomicRecommendation represents an advisory optimization recommendation for treasury or routing.
type EconomicRecommendation struct {
	RecommendationID string   `json:"recommendation_id"`
	Category         string   `json:"category"` // "TREASURY_BUFFER", "ROUTING_OPTIMIZATION", "FEE_ARBITRAGE"
	Title            string   `json:"title"`
	Rationale        string   `json:"rationale"`
	EstimatedSavings string   `json:"estimated_savings"`
	Confidence       float64  `json:"confidence"`
	ActionSteps      []string `json:"action_steps"`
}

func (e *EconomicRecommendation) Validate() error {
	if strings.TrimSpace(e.Title) == "" {
		return fmt.Errorf("title cannot be empty")
	}
	if strings.TrimSpace(e.Rationale) == "" {
		return fmt.Errorf("rationale cannot be empty")
	}
	return nil
}

// MarketplaceMatchExplanation explains why a merchant was paired with an agent request.
type MarketplaceMatchExplanation struct {
	ServiceID            string   `json:"service_id"`
	MatchScore           float64  `json:"match_score"`
	TopFactors           []string `json:"top_factors"`
	PriceCompetitiveness float64  `json:"price_competitiveness"`
	ReliabilityRating    float64  `json:"reliability_rating"`
	Summary              string   `json:"summary"`
}

func (m *MarketplaceMatchExplanation) Validate() error {
	if strings.TrimSpace(m.ServiceID) == "" {
		return fmt.Errorf("service_id cannot be empty")
	}
	if m.MatchScore < 0.0 || m.MatchScore > 1.0 {
		return fmt.Errorf("match_score must be between 0.0 and 1.0")
	}
	return nil
}

// ParseAndValidateStructured unmarshals JSON and enforces validation.
func ParseAndValidateStructured(rawJSON []byte, target interface{}) error {
	if err := json.Unmarshal(rawJSON, target); err != nil {
		return NewAIError(ErrCodeMalformedOutput, fmt.Sprintf("invalid structured JSON: %v", err), false, err)
	}

	type validator interface {
		Validate() error
	}
	if v, ok := target.(validator); ok {
		if err := v.Validate(); err != nil {
			return NewAIError(ErrCodeInvalidSchema, fmt.Sprintf("schema validation failed: %v", err), false, err)
		}
	}
	return nil
}
